// lib/mockData.ts
export type Quote = {
  symbol: string;
  price: number;
  high?: number;
  low?: number;
  previousClose?: number;
  change?: number;
  changePercent?: number;
  latestTradingDay?: string;
};

/* ---------------------- Fallback mock (estático base) ---------------------- */
export const MOCK_BASE: Record<string, Quote[]> = {
  indices: [
    {
      symbol: "SPY",
      price: 685.99,
      high: 686.86,
      low: 681.64,
      previousClose: 689.30,
      change: -3.31,
      changePercent: -0.48,
      latestTradingDay: new Date().toISOString(),
    },
    {
      symbol: "QQQ",
      price: 607.29,
      high: 610.4,
      low: 602.1,
      previousClose: 609.20,
      change: -1.91,
      changePercent: -0.31,
      latestTradingDay: new Date().toISOString(),
    },
    {
      symbol: "DIA",
      price: 497.40,
      high: 499.2,
      low: 495.1,
      previousClose: 498.60,
      change: -1.20,
      changePercent: -0.24,
      latestTradingDay: new Date().toISOString(),
    },
  ],

  acciones: [
    {
      symbol: "AAPL",
      price: 232.10,
      high: 235.4,
      low: 229.8,
      previousClose: 233.50,
      change: -1.40,
      changePercent: -0.60,
      latestTradingDay: new Date().toISOString(),
    },
    {
      symbol: "MSFT",
      price: 392.70,
      high: 397.0,
      low: 389.5,
      previousClose: 390.10,
      change: 2.60,
      changePercent: 0.66,
      latestTradingDay: new Date().toISOString(),
    },
    {
      symbol: "TSLA",
      price: 403.32,
      high: 408.0,
      low: 398.2,
      previousClose: 402.50,
      change: 0.82,
      changePercent: 0.20,
      latestTradingDay: new Date().toISOString(),
    },
    {
      symbol: "NFLX",
      price: 585.40,
      high: 590.3,
      low: 578.0,
      previousClose: 582.10,
      change: 3.30,
      changePercent: 0.57,
      latestTradingDay: new Date().toISOString(),
    },
    {
      symbol: "GOOGL",
      price: 171.60,
      high: 173.9,
      low: 169.5,
      previousClose: 170.10,
      change: 1.50,
      changePercent: 0.88,
      latestTradingDay: new Date().toISOString(),
    },
    {
      symbol: "META",
      price: 498.20,
      high: 503.1,
      low: 492.7,
      previousClose: 495.00,
      change: 3.20,
      changePercent: 0.65,
      latestTradingDay: new Date().toISOString(),
    },
    {
      symbol: "AMZN",
      price: 182.45,
      high: 184.0,
      low: 179.8,
      previousClose: 181.10,
      change: 1.35,
      changePercent: 0.75,
      latestTradingDay: new Date().toISOString(),
    },
  ],

  commodities: [
    {
      symbol: "GLD",
      price: 483.75,
      high: 486.2,
      low: 480.4,
      previousClose: 477.50,
      change: 6.25,
      changePercent: 1.31,
      latestTradingDay: new Date().toISOString(),
    },
    {
      symbol: "USO",
      price: 79.10,
      high: 80.0,
      low: 77.9,
      previousClose: 78.00,
      change: 1.10,
      changePercent: 1.41,
      latestTradingDay: new Date().toISOString(),
    },
    {
      symbol: "SLV",
      price: 84.99,
      high: 86.1,
      low: 83.4,
      previousClose: 80.50,
      change: 4.49,
      changePercent: 5.58,
      latestTradingDay: new Date().toISOString(),
    },
  ],

  crypto: [
    {
      symbol: "BTC",
      price: 66420,
      high: 68200,
      low: 63450,
      previousClose: 66800,
      change: -380,
      changePercent: -0.57,
      latestTradingDay: new Date().toISOString(),
    },
    {
      symbol: "ETH",
      price: 1990,
      high: 2050,
      low: 1930,
      previousClose: 1955,
      change: 35,
      changePercent: 1.79,
      latestTradingDay: new Date().toISOString(),
    },
    {
      symbol: "LTC",
      price: 82.4,
      high: 85.0,
      low: 80.3,
      previousClose: 83.1,
      change: -0.7,
      changePercent: -0.84,
      latestTradingDay: new Date().toISOString(),
    },
    {
      symbol: "XRP",
      price: 1.38,
      high: 1.42,
      low: 1.34,
      previousClose: 1.35,
      change: 0.03,
      changePercent: 2.22,
      latestTradingDay: new Date().toISOString(),
    },
    {
      symbol: "DOGE",
      price: 0.094,
      high: 0.098,
      low: 0.091,
      previousClose: 0.089,
      change: 0.005,
      changePercent: 5.6,
      latestTradingDay: new Date().toISOString(),
    },
    {
      symbol: "ADA",
      price: 0.28,
      high: 0.30,
      low: 0.27,
      previousClose: 0.26,
      change: 0.02,
      changePercent: 7.7,
      latestTradingDay: new Date().toISOString(),
    },
  ],

  fx: [
    {
      symbol: "EURUSD",
      price: 1.1733,
      high: 1.1794,
      low: 1.1701,
      previousClose: 1.1759,
      change: -0.0026,
      changePercent: -0.22,
      latestTradingDay: new Date().toISOString(),
    },
    {
      symbol: "USDJPY",
      price: 151.80,
      high: 152.4,
      low: 151.1,
      previousClose: 152.10,
      change: -0.30,
      changePercent: -0.20,
      latestTradingDay: new Date().toISOString(),
    },
    {
      symbol: "GBPUSD",
      price: 1.2790,
      high: 1.2840,
      low: 1.2755,
      previousClose: 1.2810,
      change: -0.002,
      changePercent: -0.16,
      latestTradingDay: new Date().toISOString(),
    },
    {
      symbol: "USDCAD",
      price: 1.3520,
      high: 1.3560,
      low: 1.3490,
      previousClose: 1.3545,
      change: -0.0025,
      changePercent: -0.18,
      latestTradingDay: new Date().toISOString(),
    },
  ],
};
