import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeSwitcher from "@/components/ui/ThemeSwitcher";
// import Image from "next/image"; //  descomentar esta línea para usar el logo

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const setInitialTheme = `(function() {
  try {
    var theme = localStorage.getItem('theme');
    if (theme === 'dark' || theme === 'light') {
      document.documentElement.setAttribute('data-theme', theme);
      if (theme === 'dark') document.documentElement.classList.add('dark');
      else document.documentElement.classList.remove('dark');
    } else if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
      document.documentElement.setAttribute('data-theme', 'dark');
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.setAttribute('data-theme', 'light');
      document.documentElement.classList.remove('dark');
    }
  } catch (e) {}
})();`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <head>
        <script dangerouslySetInnerHTML={{ __html: setInitialTheme }} />
      </head>

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* 🔹 Barra superior con logo y título */}
        <header className="flex items-center justify-between px-6 py-4 border-b border-[var(--border)]">
          <div className="flex items-center gap-3">
            {/* Espacio reservado para logo */}
            <div className="w-10 h-10 rounded-full bg-[var(--naranja-principal)]" />
            
            {/* Descomentar el bloque siguiente para usar un logo y borrar el div anterior */}
            {/* <Image
              src="/logo.png"
              alt="Logo"
              width={40}
              height={40}
              className="rounded-full"
            /> */}

            {/* Título de la marca */}
            <h1
              className="text-xl font-bold select-none"
              style={{ color: "var(--naranja-principal)" }}
            >
              Mi Página
            </h1>
          </div>

          {/* Switch de tema a la derecha */}
          <ThemeSwitcher />
        </header>

        {/* 🔹 Contenido principal */}
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}
